### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by RobertBruening** [tsugiproject/tsugi-util#3]
My team is considering using either this library or the one built with Sakai releases.  If this project can be built independently of sakai releases, it seems like the way to go. However, I see only one release in the sonatype repository and it looks like the changes from Sakai haven't been pulled in for almost a year. Is this project still going to be kept updated?

Thanks
Rob

**Comment by csev** [comment]
Yes - It is still active - I wanted to wait to copy the bits over from Sakai after Sakai made it through IMS Certification and Sakai QA for Sakai 19.  Both of those have happenned so I will bring the latest code across in a few weeks and move the version and release to sonatype.

/Chuck

**Comment by RobertBruening** [comment]
Great!  Are Apereo Contributor agreements a requirement if my team would want to propose any bugfix PRs? It's not entirely clear to me from the Apereo or Tsugi website
